# -*- coding: utf-8 -*-
"""preprocess_embed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMxmDzFuFuUJ5Hr23pZCT-pTRjpfWZ15

# General Notes
-  Considering entities as multiple tokens **not stuck together**, each token must be recognized independently from the others
- Scanning sentence left-right: since entities should be ordered we are avoiding assigning same entity to duplicate tokens

# Dependencies
"""

from itertools import product

from utils import *
from nlp_init import get_preprocessor
from loss import *




"""# Main method"""

def main(cfg, **kwargs):
    nlp = get_preprocessor()

    # DATASET
    dataset = get_dataset(kwargs["train_path"], nlp)
    labels_dict = dataset.get_labels_dict()
    train_set, valid_set = split_dataset(dataset, valid_ratio=cfg["valid_ratio"], rnd=False)
    
    train_dataloader = get_dataloader(train_set, batch_size=cfg["batch_size"], shuffle=True, collate_type='ce')
    eval_dataloader = get_dataloader(valid_set, batch_size=cfg["batch_size"], collate_type='ce')
    # test_dataloader = get_dataloader(get_dataset(kwargs["test_path"], nlp), batch_size=1)
    
    # MODEL & OTHER OBJECTS
    net = get_model(cfg["model"], labels_dict, nlp.vocab.vectors_length, cfg["hidden_size"], device=get_device())
    optimizer = get_optimizer(net, cfg["learning_rate"], cfg["optimizer"])
    loss_fn = get_loss(cfg["loss"], dataset)
    
    # TRAINING
    metrics = train(cfg["nr_epochs"], net, train_dataloader, optimizer, loss_fn, valid_dl=eval_dataloader, greedy_save=True)

    # SAVING
    _path = 'tests'
    if kwargs["save"]:
        _path = save_model(net, cfg)
        save_training(metrics, _path)
    
    # TESTING
    # TODO: automatic embedder setting
    net.set_embedder(dataset.preprocess_single_sentence)
    test_dataset = get_dataset(kwargs["test_path"], nlp)
    # test(net, test_dataset, save_path=_path)
    test_beam_search(net, test_dataset)



def produce_configurations(params):
    param_names = list(params.keys())
    configurations = product(*list(params.values()))

    for cfg in configurations:
        yield {k: v for k, v in zip(param_names, cfg)}



parameters = {
    "valid_ratio": [0.2],
    "batch_size": [64],
    "model": ["gru"],
    "loss": ["masked_ce"],
    "optimizer": ["adam"],
    "hidden_size": [200],
    "learning_rate": [1e-4],
    "nr_epochs": [15],
}


if __name__ == '__main__':

    for cfg in produce_configurations(parameters):
        print()
        print("---> Configuration: <---", *[str(k) + ": " + str(v) for k,v in cfg.items()], sep='\n')
        main(cfg, train_path = "ATIS/train.json", test_path = "ATIS/test.json", save=True)
        print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        print()



